export const options = [
    {value: "Jaco", label: "Jaco"},
    {value: "Quepos", label: "Quepos"},
    {value: "Esparza", label: "Esparza"},
    {value: "Orotina", label: "Orotina"},
    {value: "San Mateo", label: "San Mateo"},
    {value: "La Fortuna", label: "La Fortuna"},
    {value: "Ciudad Quesada", label: "Ciudad Quesada"},
    {value: "Ciudad Nelly", label: "Ciudad Nelly"},
    {value: "Buenos Aires", label: "Buenos Aires"},
    {value: "San Isidro-Pz", label: "San Isidro-Pz"},
    {value: "Alajuela", label: "Alajuela"},
    {value: "Heredia", label: "Heredia"},
    {value: "Tibas", label: "Tibas"},
    {value: "Santa Barbara", label: "Santa Barbara"},
    {value: "Santo Domingo", label: "San Isidro"},
    {value: "San Pablo-Heredia", label: "San Pablo-Heredia"},
    {value: "San Rafael-Heredia", label: "San Rafael-Heredia"},
    {value: "Barva", label: "Barva"},
    {value: "San Luis de Sto Domingo", label: "San Luis de Sto Domingo"},
    {value: "San Joaquin", label: "San Joaquin"},
    {value: "San Rafael-Alajue", label: "San Rafeal-Alajue"},
    {value: "Alajuelita", label: "Alajuelita"},
    {value: "Ciudad Colon", label: "Ciudad Colon"},
    {value: "San Sebastian", label: "San Sebastian"},
    {value: "Santa Ana", label: "Santa Ana"},
    {value: "Aurora-Alajuelita", label: "Aurora-Alajuelita"},
    {value: "Hatillo", label: "Hatillo"},
    {value: "Escazu", label: "Escazu"},
    {value: "Lomas del Rio", label: "Lomas del Rio"},
    {value: "Pavas", label: "Pavas"},
    {value: "San Antonio Belen", label: "San Antonio Belen"},
    {value: "Guápiles", label: "Guápiles"},
    {value: "Siquirres", label: "Siquirres"},
    {value: "Sarapiquí", label: "Sarapiquí"},
    {value: "Sarchí", label: "Sarchí"},
    {value: "Palmares", label: "Palmares"},
    {value: "Naranjo", label: "Naranjo"},
    {value: "San Ramón", label: "San Ramón"},
    {value: "Grecia", label: "Grecia"},
    {value: "Turrúcares", label: "Turrúcares"},
    {value: "Atenas", label: "Atenas"},
    {value: "Zarcero", label: "Zarcero"},
    {value: "Poás", label: "Poás"},
    {value: "El Guarco", label: "El Guarco"},
    {value: "Paraíso", label: "Paraíso"},
    {value: "San Juan Dios", label: "San Juan Dios"},
    {value: "Oreamuno", label: "Oreamuno"},
    {value: "Desamparados", label: "Desamparados"},
    {value: "San Rafael Arriba", label: "San Rafael Arriba"},
    {value: "San Rafael Abajo", label: "San Rafael Abajo"},
    {value: "Tres Rios", label: "Tres Rios"},
    {value: "El Molino", label: "El Molino"},
    {value: "Coronado", label: "Coronado"},
    {value: "Curridabat", label: "Curridabat"},
    {value: "Plaza Víquez", label: "Plaza Víquez"},
    {value: "Zapote", label: "Zapote"},
    {value: "Vargas Araya", label: "Vargas Araya"},
    {value: "La Capri", label: "La Capri"},
    {value: "Villas de Ayarco", label: "Villas de Ayarco"},
    {value: "Frailes", label: "Frailes"},
    {value: "San Pedro", label: "San Pedro"},
    {value: "Liberia", label: "Liberia"},
    {value: "Santa Cruz", label: "Santa Cruz"},
    {value: "Nicoya", label: "Nicoya"}
]